# Assignment 1 — Advanced NumPy

# Advanced NumPy — vectorization, broadcasting, views vs copies, dtypes, performance tips

In [1]:
import numpy as np
np.__version__

'2.3.3'

In [2]:
# Creation & dtypes
a = np.arange(12).reshape(3,4)
b = np.linspace(0, 1, 5)
i16 = np.array([1,2,3], dtype=np.int16)
print(a, a.shape)
print(b)
print(i16, i16.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[0.   0.25 0.5  0.75 1.  ]
[1 2 3] int16


In [3]:
# Views vs copies
x = np.arange(10)
view = x[2:7]     # view
copy = x[2:7].copy()
view[:] = -1
print("x:", x)
print("view:", view)
print("copy:", copy)

x: [ 0  1 -1 -1 -1 -1 -1  7  8  9]
view: [-1 -1 -1 -1 -1]
copy: [2 3 4 5 6]


In [4]:
# Broadcasting
A = np.arange(6).reshape(2,3)
v = np.array([10,20,30])
print(A + v)  # row-wise broadcast
print((A.T + np.array([100, 100])).T)  # column-wise broadcast trick

[[10 21 32]
 [13 24 35]]
[[100 101 102]
 [103 104 105]]


In [5]:
# Fancy indexing & boolean masks
M = np.arange(1,26).reshape(5,5)
mask = (M % 2 == 0) & (M > 10)
print(M[mask])
rows = [0,2,4]; cols = [1,3,0]
print(M[rows, cols])

[12 14 16 18 20 22 24]
[ 2 14 21]


In [6]:
# Aggregations & axis semantics
X = np.arange(12).reshape(3,4)
print("sum:", X.sum(), "row-sum:", X.sum(axis=1), "col-mean:", X.mean(axis=0))

sum: 66 row-sum: [ 6 22 38] col-mean: [4. 5. 6. 7.]


In [7]:
# Linear algebra
A = np.array([[3,1],[1,2]], dtype=float)
eigvals, eigvecs = np.linalg.eig(A)
invA = np.linalg.inv(A)
x = np.linalg.solve(A, np.array([9,8]))
print(eigvals)
print(invA)
print("solution to Ax=b:", x)

[3.61803399 1.38196601]
[[ 0.4 -0.2]
 [-0.2  0.6]]
solution to Ax=b: [2. 3.]


In [8]:
# Vectorization vs Python loops (timing)
import time
n = 2_000_00
arr = np.random.rand(n)
start = time.time()
total = 0.0
for v in arr:
    total += v*v
loop_time = time.time() - start

start = time.time()
total_np = np.sum(arr*arr)
vec_time = time.time() - start

print(f"loop_time={loop_time:.4f}s, vec_time={vec_time:.4f}s, speedup≈{loop_time/vec_time:.1f}x")

loop_time=0.0321s, vec_time=0.0005s, speedup≈66.3x


In [9]:
# Random & reproducibility
rng = np.random.default_rng(42)
print(rng.normal(size=5))
print(rng.integers(0, 10, size=(2,3)))

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
[[5 9 7]
 [7 7 7]]


**Exercises**
1. Create a 1000x1000 random matrix and compute the cosine similarity between all rows.
2. Implement z-score normalization with broadcasting.
3. Replace all values below the column medians with the median.
